### ISSUE TITLE
I can't install the app on my Google Pixel 7 pro

### ISSUE THREAD

**Issue by JuanRodenas** [yang991178/fluent-reader-lite#107]
**Describe the bug**
I try to install the application through the Google play store on Google Pixel 7 pro and I get a message:

_This app is not available on your device because it was created for an older version of Android._

**To Reproduce**
1. Open repository of app
2. Click on Play Store
3. Open Play store

**Expected behavior**
I want to install the app on my google pixel to buy the app to support the project.

**Screenshots**
![Screenshot_20230913-000753.png](https://github.com/yang991178/fluent-reader-lite/assets/95724863/accded5f-c90f-4ac2-8ad1-49d2c9300314)

**Platform (please complete the following information):**
 - Android 13
 - Google Pixel 7 pro

**Comment by yang991178** [comment]
Thanks for flagging this. I've submitted a new version to Google Play with a higher target API level, hopefully that should be reviewed by the Play team soon.
