### ISSUE TITLE
【性能问题：mysql会被100%读写IO占满】

### ISSUE THREAD

**Issue by Whichbfj28** [yang991178/fluent-reader-lite#15]
【性能问题：mysql会被100%读写IO占满】：
ttrss+mysql5.7+php7+fever，已储存20W+feed，
fluent-reader-lite设置1500的同步数量的情况下。用app阅读feed20分钟后。设置某个源全部已读会导致mysql读写100%。
官方自带的ttrss软件无此问题

**Comment by yang991178** [comment]
这应该是ttrss本身的问题？将某个源全部标为已读只是一个Fever API调用，服务端具体的实现与本应用应该是没有关系的

**Comment by Whichbfj28** [comment]
> 这应该是ttrss本身的问题？将某个源全部标为已读只是一个Fever API调用，服务端具体的实现与本应用应该是没有关系的

1.ttrss官方ios app没这个问题。只是官方的app不好用。
2.我怀疑是因为fever要把所有这个源的数据库读取出来再写入进去的导致的，
3.官方的app可能只是写入单独数据库的表行即可。说到底我还是怀疑fever效率不行。
4.其实我用了很多的ttrss的ios阅读器都不好用。包括reeder。readkit. fiery 这几个都是付费的。这些的app最大的问题都是要把整个ttrss数据库下载下来。但是我的ttrss数据库太大了。导致这些app标记为已读的时候直接把数据库卡死。不知道作者有没有改进的想法。换了那么多的app真心有点累了。

**Comment by yang991178** [comment]
TTRSS的Fever插件也不是官方维护的，插件的问题这里也无法解决，这个issue就先close了。
