### ISSUE TITLE
能否添加本地订阅RSS功能呢？

### ISSUE THREAD

**Issue by Yikng** [yang991178/fluent-reader-lite#20]
如题，能否添加本地订阅RSS功能呢？Fluent Reader PC很好用。奇怪得是，Fluent Reader PC端得本地订阅功能到了移动端却没有了。考虑到Fluent Reader移动端提供的服务在中国都被屏蔽了，因此本地Rss订阅服务是用户最好的解决办法。因此，请求考虑增加本地订阅功能。

can I add a local RSS subscription function? Fluent Reader PC is easy to use. Strangely enough, the local subscription function on the PC side of Fluent Reader is not available on the mobile side. Considering that the services provided by the mobile terminal of Fluent Reader have been blocked in China, the local Rss subscription service is the best solution for users. Therefore, it is requested to consider adding local subscription features.

**Comment by yang991178** [comment]
Inoreader，Feedbin，The Old Reader 和自建服务器都能在墙内正常使用。这个应用设计就是为了和桌面端同步，个人精力有限没有支持本地抓取的打算。#3
