### ISSUE TITLE
Local sources

### ISSUE THREAD

**Issue by D3SOX** [yang991178/fluent-reader-lite#24]
**Is your feature request related to a problem? Please describe.**
I don't use any RSS sync service and would like to use it locally.

**Describe the solution you'd like**
Just like in the desktop version

**Comment by yang991178** [comment]
#3

**Comment by D3SOX** [comment]
Sorry, I did not search through the closed issues. Why don't you want to add this? Would you accept a PR adding it (I'm not that familiar with flutter/dart so I'd have to learn it a bit first)

**Comment by yang991178** [comment]
> Sorry, I did not search through the closed issues. Why don't you want to add this? Would you accept a PR adding it (I'm not that familiar with flutter/dart so I'd have to learn it a bit first)

Properly parsing and managing local sources is quite a nontrivial task and I don't have the time to work on something that I won't use. Besides, the point of this app is to sync with the desktop app. I'd much prefer people to just use that instead for a better experience if they don't need syncing.
