### ISSUE TITLE
Local RSS support?

### ISSUE THREAD

**Issue by Pentaphon** [yang991178/fluent-reader-lite#3]
As the title says, can we get local RSS support? 

Not everybody is using a feed service. This is especially needed if you can't add Feedly support.

**Comment by yang991178** [comment]
I will not work on local RSS support in this app. You can use the desktop app or many other mobile apps if you need local RSS.

**Comment by geekedtv** [comment]
> 

“Any other rss app? It’s quite misleading to pay for the app only to find out we can’t even add external RSS feeds. Another app I can’t use. I don’t use rss services.
