### ISSUE TITLE
加入后台刷新并进行通知？

### ISSUE THREAD

**Issue by GGboomers** [yang991178/fluent-reader-lite#32]
后台刷新并通知可以及时获取信息，方便又高效

**Comment by yang991178** [comment]
#4 
由于ios的平台限制通知只能由服务端推送

**Comment by GGboomers** [comment]
安卓也限制？？



---原始邮件---
发件人: "Haoyuan ***@***.***&gt;
发送时间: 2021年3月29日(周一) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yang991178/fluent-reader-lite] 加入后台刷新并进行通知？ (#32)




 
#4
 由于ios的平台限制通知只能由服务端推送
