### ISSUE TITLE
Two-pane view feature not found in Android Tablet Matepad 11

### ISSUE THREAD

**Issue by Latias94** [yang991178/fluent-reader-lite#42]
**Describe the bug**
Two-pane view feature not found in Android Tablet Matepad 11.

**To Reproduce**
Open App.

**Expected behavior**
Two-pane view.

**Screenshots**
![Screenshot_20210717_150950_me hyliu fluent_reader_lite](https://user-images.githubusercontent.com/13315417/126029595-e2b0494d-82f7-4e8c-a7b2-a4e4d82dfcca.jpg)

**Platform (please complete the following information):**
 - OS: [Harmony OS]
 - Version [2.0.0.137]
 - App Version [1.0.2(8)]

**Additional context**
Is there a setting to enable it or else?

**Comment by yang991178** [comment]
The shortest edge of the screen need to be wider than 640pt to be considered a tablet for now.

**Comment by Latias94** [comment]
> The shortest edge of the screen needs to be wider than 640pt to be considered as a tablet for now.

It will be great if there has a setting to force enable it.
