### ISSUE TITLE
是否可以增加以系统浏览器打开文章的选项，方便类似B站的信息通过safari调用B站app打开

### ISSUE THREAD

**Issue by Qeynos** [yang991178/fluent-reader-lite#50]
我使用freshrss并且通过rsshub订阅文章以及B站的特定几个人的视频，ipad上一直用的是Reeder，试用了一下fluent reader lite感觉非常清爽，但开打的时候使用内置浏览器，登录记录不能一直保持，并且浏览器看视频的体验比不上app

Reeder的一个功能是可以open in safari，实际效果是直接调用了bilibili应用，虽然需要进行几次点击，但至少是可以实现的，如果fluent reader lite可以实现这个功能，我想可能可以让很多订阅视频的人更方便，

**Comment by yang991178** [comment]
在`设置>信息流>手势`中可以设置在外部打开，或者每个订阅源都可以单独设置打开方式。在外部打开是调用系统默认打开url的方式，如果应用支持是可以直接打开的。

**Comment by Qeynos** [comment]
尝试了确实可以实现，非常好用

另一个问题，就是信息流能否选择分类，订阅源里选择分类并不能看信息流，而信息流里不能看具体分类的信息流，我觉得这是一个基础功能，例如分类有视频、文字、更新提醒等，不同场景下需要看特定的分类流，不知是我没找到用法还是有开发计划

**Comment by yang991178** [comment]
> 另一个问题，就是信息流能否选择分类

`订阅源>分组>某一分组>全部文章`

**Comment by Qeynos** [comment]
> > 另一个问题，就是信息流能否选择分类
> 
> `订阅源>分组>某一分组>全部文章`

这个操作很深啊，而且关闭以后重新进入还要重新选
是否可以在信息流里提供分类的查看，从操作逻辑上比较合理
