### ISSUE TITLE
如何使用ipad版本，macbook用过所以下了ipad版本，发现进去完全不一样，请教第一步如何使用

### ISSUE THREAD

**Issue by steconme** [yang991178/fluent-reader-lite#51]
如何使用ipad版本，macbook用过所以下了ipad版本，发现进去完全不一样，请教第一步如何使用，没有找到倒入opml文件的地方：（

**Comment by yang991178** [comment]
移动端与桌面端不是同一个应用，移动端不支持从设备抓取rss，只支持与服务同步。

> 此应用 *不包括* 以下桌面版的功能：
> * 本地 RSS 支持或在本地管理订阅源/分组
> * 导入/导出 OPML 文件或备份/还原应用设置
> * 基于正则表达式标记文章的规则
> * 在后台抓取文章并发送推送通知
> * 键盘快捷键
