### ISSUE TITLE
distinguish the output style of read and unread articles

### ISSUE THREAD

**Issue by RikkaBlue** [yang991178/fluent-reader-lite#6]
希望能在区分显示已读和未读文章。

![IMG_20210129_110249](https://user-images.githubusercontent.com/46104879/106226162-8df4b700-6221-11eb-917c-f98ccbad45f2.jpg)

例如灰色标题等。

**Comment by yang991178** [comment]
默认情况已读文章右上角有橙色指示，如果需要灰色标题可以在 “设置>信息流>淡化已读文章” 里打开。
