### ISSUE TITLE
Separate API code to a library

### ISSUE THREAD

**Issue by FunctionalHacker** [yang991178/fluent-reader-lite#7]
Hi! I'm looking to start a project to learn Dart and Flutter by creating a greader compatible RSS app. I was happy to find that someone has alredy started such a project. 

I was hoping to find a ready made Dart library for using the greader API, but unfortunately there seems to be none available. I started looking the part of your code that handles the services [here](https://github.com/yang991178/fluent-reader-lite/tree/master/lib/models/services) and had an idea to create a separate library based around this code. This way, other developers like me could easily create apps that use these API's, and you could possibly even use this library in fluent-reader-lite.

What do you think about this? I will probably do this anyway, respecting the license of this project of course, but I wanted to give you a heads up. When the library is completed (might take a while, as I'm just starting with Dart), I can add you as a co-maintainer to the repository so we can join forces maintaining the API code.

**Comment by yang991178** [comment]
Personally speaking I'm not a big fan of Google Reader API and different RSS services seem to have different interpretations of it. The way that this app handles the Reader API right now is pretty inelegant and has some compatibility issues with FreshRSS (see FreshRSS/FreshRSS#3389). This app also only uses a very small fraction of the data and functionalities of the API currently. 

That being said, please feel free to reuse and repurpose the code in this repo as permitted by the license.

**Comment by FunctionalHacker** [comment]
Alright, thanks for the heads up. I will probably implement both greader and fever, since that's what FreshRSS supports and it's the server of my choice. Don't know much about the benefits of one over the other but I guess I'm at a better place to judge after implementing both.

I will leave this issue open in case you are interested in using the separate library in fluent-reader-lite. If not, feel free to close this.

**Comment by FunctionalHacker** [comment]
I will be be pushing my work to this repository if anyone is interested: https://github.com/FunctionalHacker/fluent-reader-lib

**Comment by yang991178** [comment]
Thanks, I'll probably take a look later. I would suggest using another name for the repo for better compliance with the third clause of the BSD license though.
